---
title: "Data Mining 3"
author: "Simge Çınar"
date: "2024-02-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RWeka)
```

```{r}
df <- read.arff("/Users/simgecinar/Desktop/monk1.arff")
df
```
```{r}
summary(df)
```
```{r}
new1 <- df[df$`attribute#1` == 1 & df$`attribute#2` == 1, ]
table(new1$class)

new2 <- df[df$`attribute#1` == 2 & df$`attribute#2` == 2, ]
table(new2$class)

new3 <- df[df$`attribute#1` == 3 & df$`attribute#2` == 3, ]
table(new3$class)
```

```{r}
9+15+17- (1+3+4) + 29
```

```{r}
new1 <- df[df$`attribute#1` == 1 & df$`attribute#2` == 1 & df$`attribute#5` != 1, ]
nrow(new1[new1$class == 1, ])
```


```{r}
new1 <- df[df$`attribute#1` == 1 & df$`attribute#2` == 1 & df$`attribute#5` != 1, ]
r1 <- nrow(new1[new1$class == 1, ])
r1

new2 <- df[df$`attribute#1` == 2 & df$`attribute#2` == 2 & df$`attribute#5` != 1, ]
r2 <- nrow(new2[new2$class == 1, ])
r2

new3 <- df[df$`attribute#1` == 3 & df$`attribute#2` == 3 & df$`attribute#5` != 1, ]
r3 <- nrow(new3[new3$class == 1, ])
r3

new4 <- df[df$`attribute#5` == 1 , ]
r4 <- nrow(new4[new4$class == 1, ])
r4

r1 + r2 + r3 + r4
```


```{r}
df1 <- df[df$class == 1, ]
summary(df1)
```
```{r}
df0 <- df[df$class == 0 , ]
summary(df0)
```

```{r}
cont_table <- table(df1$`attribute#1`, df1$`attribute#2`)
names(dimnames(cont_table)) <- c("attribute#1", "attribute#2")
cont_table
```

```{r}
cont_table <- table(df$`attribute#1`, df$class)
names(dimnames(cont_table)) <- c("attribute#1", "Class")
cont_table
#chisq_test <- chisq.test(cont_table)
#print(chisq_test)

# chi-square test value is less than 0.05 for attribute#1 and attribute#5

cont_table <- table(df$`attribute#2`, df$class)
names(dimnames(cont_table)) <- c("attribute#2", "Class")
cont_table
```


```{r}
# Create a contingency table
cont_table <- table(df$`attribute#1`, df$`attribute#2`)
cont_table

# Perform chi-square test to check if there's a significant association
chisq_test <- chisq.test(cont_table)
print(chisq_test)

# Calculate Phi coefficient
phi_coefficient <- sqrt(chisq_test$statistic / sum(cont_table))
print(paste("Phi Coefficient:", phi_coefficient))

# Check association between attribute 5 and class label
cont_table_attr1_class <- table(df$`attribute#1`, df$class)
print(chisq.test(cont_table_attr1_class))

# Check association between attribute 6 and class label
cont_table_attr2_class <- table(df$`attribute#2`, df$class)
print(chisq.test(cont_table_attr2_class))
```



```{r}
# Create a contingency table
cont_table <- table(df$`attribute#2`, df$`attribute#3`)

# Perform chi-square test to check if there's a significant association
chisq_test <- chisq.test(cont_table)
print(chisq_test)

# Calculate Phi coefficient
phi_coefficient <- sqrt(chisq_test$statistic / sum(cont_table))
print(paste("Phi Coefficient:", phi_coefficient))

# Check association between attribute 5 and class label
cont_table_attr2_class <- table(df$`attribute#2`, df$class)
print(chisq.test(cont_table_attr2_class))

# Check association between attribute 6 and class label
cont_table_attr3_class <- table(df$`attribute#3`, df$class)
print(chisq.test(cont_table_attr3_class))
```

